### ISSUE TITLE
What does this add'on do?

### ISSUE THREAD

**Issue by fredvd** [collective/collective.iconifiedcategory#1]
The readme on github or pypi has no indication of what this add'on is providing.

**Comment by gbastien** [comment]
Hi @fredvd 

sorry I did not see your question...  I completed the README to explain briefly what this addon do, I hope you see how it works.  This is a work in progress but it reached now a stable state and we use it on production on several instances.

I will try to add screenshots as soon as possible.

If you come at the PloneConf 2017 we can talk about it and we may show you custom implementations we made with it.

+++

Gauthier
